import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		default: "Next.js tutorial - Codevolution",
		absolute: "%s | Codevolution",
		template: ""
	},
	description: "Generated by Next.js"
};

export default function AuthLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	);
}
